steps:

# 依存関係の解決
- name: 'gcr.io/cloud-builders/go'
  env:
    - PROJECT_ROOT=$PROJECT_ID/$REPO_NAME
  entrypoint: ash
  args:
  - '-c'
  - |
    . /builder/prepare_workspace.inc
    prepare_workspace || exit
    gp=$(go env GOPATH)
    go get -u github.com/golang/dep/cmd/dep
    $gp/bin/dep ensure

# アプリケーションのビルド
- name: 'gcr.io/cloud-builders/go'
  env:
    - PROJECT_ROOT=$PROJECT_ID/$REPO_NAME
  args: ['build']

# DockerImageのビルド
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest', '.' ]
  id: 'docker-build'

# GKEへデプロイ
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'fin_mane_be.yaml']
  env:
    - CLOUDSDK_COMPUTE_ZONE=asia-northeast-1
    - CLOUDSDK_CONTAINER_CLUSTER=cluster-1
  waitFor: ['docker-build']

images: ['gcr.io/$PROJECT_ID/$REPO_NAME']