apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fin-mane-be
  namespace: fin-mane
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fin-mane-be
    spec:
      containers:
      - name: fin-mane-be
        image: gcr.io/fin-mane/github-sert-uw-fin_mane_be:latest
        resources:
          requests:
            cpu: 10m
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: '8080'
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DB_IP
          value: '127.0.0.1'
        - name: DB_PORT
          value: '3306'
        - name: CREDENTIALS
          value: /secrets/firebase/credentials.json
        volumeMounts:
        - name: firebase-credentials
          mountPath: /secrets/firebase
          readOnly: true

      - image: gcr.io/cloudsql-docker/gce-proxy:1.09
        name: cloudsql-proxy
        resources:
          requests:
            cpu: 10m
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=fin-mane:asia-northeast1:fin-mane=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
        - name: ssl-certs
          mountPath: /etc/ssl/certs
        - name: cloudsql
          mountPath: /cloudsql

      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs
      - name: cloudsql
        emptyDir:
      - name: firebase-credentials
        secret:
          secretName: firebase-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: fin-mane-be
  namespace: fin-mane
  labels:
    app: fin-mane-be
spec:
  type: NodePort
  selector:
    app: fin-mane-be
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fin-mane-be
  namespace: fin-mane
spec:
  rules:
  - host: fin-mane-be.d-sert.com
    http:
      paths:
      - backend:
          serviceName: fin-mane-be
          servicePort: 80